# Use the default GitHub Codespaces image
# https://github.com/devcontainers/images/blob/main/src/universal/history/2.5.1.md
FROM mcr.microsoft.com/vscode/devcontainers/universal:2.5.1-focal

# Install Xvfb
RUN sudo apt-get update && sudo apt-get install -y xvfb && sudo apt-get clean

